"use client";
import { useCallback,useEffect,useState } from "react";
import { Onboarding } from "@/components/Onboarding";import { Header } from "@/components/Header";import { WeekView } from "@/components/WeekView";import { GroceryView } from "@/components/GroceryView";import { ProfileView } from "@/components/ProfileView";import { Button,Modal,Spinner } from "@/components/ui";
import { getGrocery,getHousehold,getMembers,getMeals,getOrCreateWeek,getApprovalsForWeek,deleteGroceryItem,deleteMeal,generateGroceryFromMeals,resetDemoData,saveGroceryItem,saveMeal,setApproval as dbSetApproval,subscribe,saveMember,getMealLibrary,saveDish } from "@/lib/db";
import type { Approval,ApprovalStatus,GroceryItem,Household,Meal,MealType,Member,SavedDish,Week } from "@/lib/types";import { startOfWeek,toISODate,addDays } from "@/lib/dates";import { CalendarDays,ShoppingCart,Users,RotateCcw } from "lucide-react";import { cn } from "@/lib/cn";import { useTheme } from "@/lib/useTheme";import { IS_DEMO } from "@/lib/supabase";import { storageGet,storageSet } from "@/lib/storage";
interface Session{householdId:string;memberId:string;name:string;role:"gardienne"|"parent"}const uid=()=>crypto?.randomUUID?.()??"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx";
export default function Page(){const{theme,toggle}=useTheme();const[session,setSession]=useState<Session|null>(null),[restored,setRestored]=useState(false),[weekStart,setWeekStart]=useState(startOfWeek(new Date())),[household,setHousehold]=useState<Household|null>(null),[members,setMembers]=useState<Member[]>([]),[week,setWeek]=useState<Week|null>(null),[meals,setMeals]=useState<Meal[]>([]),[approvals,setApprovals]=useState<Approval[]>([]),[grocery,setGrocery]=useState<GroceryItem[]>([]),[library,setLibrary]=useState<SavedDish[]>([]),[loading,setLoading]=useState(true),[view,setView]=useState<"semaine"|"epicerie"|"profils">("semaine"),[membersOpen,setMembersOpen]=useState(false),[pendingGrocery,setPendingGrocery]=useState(false);
 useEffect(()=>{const raw=storageGet("repas-garde-session");if(raw)setSession(JSON.parse(raw));setRestored(true)},[]);useEffect(()=>{if(session)storageSet("repas-garde-session",JSON.stringify(session))},[session]);
 const loadAll=useCallback(async()=>{if(!session)return;const[h,mem]=await Promise.all([getHousehold(session.householdId),getMembers(session.householdId)]);setHousehold(h);setMembers(mem);const w=await getOrCreateWeek(session.householdId,toISODate(weekStart));setWeek(w);const[ml,ap,gr,lib]=await Promise.all([getMeals(w.id),getApprovalsForWeek(w.id),getGrocery(w.id),getMealLibrary(session.householdId)]);setMeals(ml);setApprovals(ap);setGrocery(gr);setLibrary(lib);setLoading(false)},[session,weekStart]);
 useEffect(()=>{if(!session)return;const u=subscribe(loadAll);loadAll();return()=>{u();setLoading(true)}},[session,loadAll]);
 const addMeal=async(day:number,type:MealType)=>{if(!week)return;await saveMeal({id:uid(),week_id:week.id,day_index:day,meal_type:type,title:"",description:"",ingredients:[],notes:"",updated_by:session?.name})};
 const saveMealAndLibrary=async(meal:Meal)=>{await saveMeal({...meal,updated_by:session?.name});if(session&&meal.title.trim())await saveDish({id:`${session.householdId}-${meal.title.trim().toLowerCase()}`,household_id:session.householdId,title:meal.title.trim(),description:meal.description,ingredients:meal.ingredients,notes:meal.notes});};
 const generate=async()=>{if(!week)return;setPendingGrocery(true);try{await generateGroceryFromMeals(week.id,session?.name||"");setView("epicerie")}finally{setPendingGrocery(false)}};
 if(!restored)return <Spinner/>;if(!session)return <Onboarding onReady={(householdId,memberId,name,role)=>setSession({householdId,memberId,name,role})}/>;if(loading||!household)return <Spinner/>;
 const tabs=[{id:"semaine" as const,label:"Soupers",icon:CalendarDays},{id:"epicerie" as const,label:"Liste de course",icon:ShoppingCart},{id:"profils" as const,label:"Profils",icon:Users}];
 return <div className="min-h-dvh"><Header householdName={household.name} inviteCode={household.invite_code} memberName={session.name} memberRole={session.role} theme={theme} onToggleTheme={toggle} onOpenMembers={()=>setMembersOpen(true)} childrenCount={members.length}/><nav className="sticky top-14 z-20 border-b border-border bg-surface/85 backdrop-blur"><div className="max-w-6xl mx-auto px-3 sm:px-4 flex">{tabs.map(t=><button key={t.id} onClick={()=>setView(t.id)} className={cn("flex items-center gap-1.5 px-3 py-2.5 text-sm font-medium border-b-2 -mb-px",view===t.id?"border-primary text-primary":"border-transparent text-muted")}>{<t.icon size={16}/>} {t.label}{t.id==="epicerie"&&grocery.filter(g=>!g.checked).length>0&&<span className="ml-1 text-xs bg-primary text-white rounded-full px-1.5">{grocery.filter(g=>!g.checked).length}</span>}</button>)}</div></nav><main className="max-w-6xl mx-auto px-3 sm:px-4 py-4">{view==="semaine"&&<WeekView week={week} meals={meals} approvals={approvals} members={members} currentMemberId={session.memberId} currentMemberName={session.name} currentRole={session.role} weekStart={weekStart} onWeekChange={d=>{setLoading(true);setWeekStart(startOfWeek(d))}} onSaveMeal={saveMealAndLibrary} onDeleteMeal={deleteMeal} onSetApproval={(id,s,c)=>dbSetApproval(id,session.memberId,s,c,session.name)} onAddMeal={addMeal} onGenerateGrocery={generate} pendingGrocery={pendingGrocery} library={library}/>} {view==="epicerie"&&<GroceryView items={grocery} currentRole={session.role} currentMemberName={session.name} onAdd={saveGroceryItem} onUpdate={i=>saveGroceryItem({...i,updated_by:session.name})} onDelete={deleteGroceryItem} onToggle={(id,checked)=>{const i=grocery.find(x=>x.id===id);if(i)saveGroceryItem({...i,checked,updated_by:session.name})}}/>}{view==="profils"&&<ProfileView members={members} householdId={session.householdId} onSave={saveMember}/>}</main><MembersModal open={membersOpen} onClose={()=>setMembersOpen(false)} members={members} inviteCode={household.invite_code} currentRole={session.role} onResetDemo={IS_DEMO?()=>{resetDemoData();setSession(null)}:undefined}/></div>}
function MembersModal({open,onClose,members,inviteCode,currentRole,onResetDemo}:{open:boolean;onClose:()=>void;members:Member[];inviteCode:string;currentRole:"gardienne"|"parent";onResetDemo?:()=>void}){return <Modal open={open} onClose={onClose} title="Membres du foyer"><div className="space-y-3"><div className="rounded-lg bg-primary-soft p-3"><p className="text-xs text-primary">Code d'invitation</p><p className="font-mono text-2xl tracking-[0.3em] text-center py-2 font-bold">{inviteCode}</p></div>{members.map(m=><div key={m.id} className="flex items-center gap-2"><div className="h-7 w-7 rounded-full text-white flex items-center justify-center text-xs font-bold" style={{background:m.profile_color||"#7c3aed"}}>{m.name[0]}</div><span className="text-sm">{m.name}</span><span className="text-xs text-faint ml-auto">{m.role}</span></div>)}{currentRole==="gardienne"&&onResetDemo&&<Button variant="ghost" size="sm" onClick={onResetDemo} className="text-danger"><RotateCcw size={14}/> Réinitialiser la démo</Button>}</div></Modal>}
