"use client";
import { useState } from "react";
import type { Approval, ApprovalStatus, Member, Meal, SavedDish } from "@/lib/types";
import { APPROVAL_META, MEAL_LABEL } from "@/lib/types";
import { Badge, Button, Input, Modal, Textarea } from "@/components/ui";
import { Pencil, Trash2, AlertTriangle, BookOpen } from "lucide-react";
import { cn } from "@/lib/cn";

export function MealCard({meal,members,approvals,currentMemberId,currentMemberName,currentRole,onSave,onDelete,onSetApproval,library}:{meal:Meal;members:Member[];approvals:Approval[];currentMemberId:string;currentMemberName:string;currentRole:"gardienne"|"parent";onSave:(meal:Meal)=>void;onDelete:()=>void;onSetApproval:(status:ApprovalStatus,comment:string)=>void;library:SavedDish[]}){
 const [editing,setEditing]=useState(false); const [comment,setComment]=useState(approvals.find(a=>a.member_id===currentMemberId)?.comment||""); const [libraryOpen,setLibraryOpen]=useState(false);
 const mine=approvals.find(a=>a.member_id===currentMemberId); const parents=members.filter(m=>m.role==="parent"); const approved=approvals.filter(a=>a.status==="approved").length; const rejected=approvals.some(a=>a.status==="not_ok");
 const statusText=rejected?"Refusé par un parent":parents.length&&approved===parents.length?"Validé par tous":`${approved}/${parents.length} parents`;
 const saveComment=()=>onSetApproval(mine?.status||"change_requested",comment);
 return <>
  <div className="rounded-lg border border-border bg-surface p-3 hover:shadow-sm transition group">
   <div className="flex items-start justify-between gap-2"><h4 className="font-semibold text-sm">{meal.title||"Repas à définir"}</h4>{currentRole==="gardienne"&&<div className="flex gap-1 opacity-0 group-hover:opacity-100"><button onClick={()=>setEditing(true)} className="p-1 text-faint hover:text-primary"><Pencil size={14}/></button><button onClick={onDelete} className="p-1 text-faint hover:text-danger"><Trash2 size={14}/></button></div>}</div>
   {meal.description&&<p className="text-xs text-muted mt-1">{meal.description}</p>}
   {meal.ingredients.length>0&&<div className="flex flex-wrap gap-1 mt-2">{meal.ingredients.map((x,i)=><span key={i} className="text-xs bg-offset text-muted rounded px-1.5 py-0.5">{x}</span>)}</div>}
   {meal.notes&&<p className="text-xs text-warning flex gap-1 mt-2"><AlertTriangle size={12}/> {meal.notes}</p>}
   <div className="flex items-center justify-between pt-2 mt-2 border-t border-divider"><Badge className="bg-offset text-muted">{rejected?"✕":"○"} {statusText}</Badge></div>
  </div>
  {currentRole==="parent"&&<div className="mt-1 rounded-md bg-offset/60 p-2"><label className="text-[11px] font-medium text-muted">Commentaire pour ce souper</label><div className="flex gap-2 mt-1"><Input value={comment} onChange={e=>setComment(e.target.value)} onBlur={saveComment} placeholder="Pas de noix, il n'aime pas le poisson…"/><Button size="sm" variant="soft" onClick={saveComment}>Enregistrer</Button></div></div>}
  <MealEditDialog open={editing} onClose={()=>setEditing(false)} meal={meal} library={library} onPick={m=>{onSave({...meal,title:m.title,description:m.description,ingredients:m.ingredients,notes:m.notes});setEditing(false)}} onSave={m=>{onSave(m);setEditing(false)}} onOpenLibrary={()=>setLibraryOpen(true)} />
  <Modal open={libraryOpen} onClose={()=>setLibraryOpen(false)} title="Bibliothèque de plats"><div className="space-y-2">{library.length===0?<p className="text-sm text-muted">Aucun plat enregistré pour l'instant. Enregistre un souper pour le retrouver ici.</p>:library.map(d=><button key={d.id} onClick={()=>{onSave({...meal,title:d.title,description:d.description,ingredients:d.ingredients,notes:d.notes});setLibraryOpen(false);setEditing(false)}} className="w-full text-left rounded-lg border border-border p-3 hover:bg-offset"><div className="font-medium text-sm">{d.title}</div><div className="text-xs text-muted mt-1">{d.ingredients.join(" · ")}</div></button>)}</div></Modal>
 </>;
}
function MealEditDialog({open,onClose,meal,onSave,library,onOpenLibrary}:{open:boolean;onClose:()=>void;meal:Meal;onSave:(m:Meal)=>void;library:SavedDish[];onOpenLibrary:()=>void;onPick:(m:SavedDish)=>void}){const [title,setTitle]=useState(meal.title),[description,setDescription]=useState(meal.description),[ingredients,setIngredients]=useState(meal.ingredients.join("\n")),[notes,setNotes]=useState(meal.notes);const [last,setLast]=useState("");if(open&&last!==meal.id){setLast(meal.id);setTitle(meal.title);setDescription(meal.description);setIngredients(meal.ingredients.join("\n"));setNotes(meal.notes)}return <Modal open={open} onClose={onClose} wide title={`${MEAL_LABEL[meal.meal_type]} — modifier`} footer={<><Button variant="ghost" onClick={onClose}>Annuler</Button><Button onClick={()=>onSave({...meal,title:title.trim(),description:description.trim(),ingredients:ingredients.split("\n").map(x=>x.trim()).filter(Boolean),notes:notes.trim()})}>Enregistrer</Button></>}><div className="space-y-3"><Button variant="soft" className="w-full" onClick={onOpenLibrary}><BookOpen size={14}/> Piger dans la bibliothèque de plats</Button><div><label className="text-xs font-medium text-muted">Nom du plat</label><Input value={title} onChange={e=>setTitle(e.target.value)} className="mt-1"/></div><div><label className="text-xs font-medium text-muted">Description</label><Textarea value={description} onChange={e=>setDescription(e.target.value)} className="mt-1"/></div><div><label className="text-xs font-medium text-muted">Ingrédients (un par ligne)</label><Textarea value={ingredients} onChange={e=>setIngredients(e.target.value)} className="mt-1 min-h-[100px]"/></div><div><label className="text-xs font-medium text-muted">Notes / alertes</label><Textarea value={notes} onChange={e=>setNotes(e.target.value)} className="mt-1"/></div><p className="text-xs text-faint">{library.length} plat(s) enregistré(s)</p></div></Modal>}
