"use client";
import { useState } from "react";
import type { Member } from "@/lib/types";
import { PROFILE_COLORS } from "@/lib/types";
import { Button, EmptyState, Input, Modal, Textarea } from "@/components/ui";
import { Plus, Pencil, Users } from "lucide-react";

export function ProfileView({ members, householdId, onSave }: { members: Member[]; householdId: string; onSave: (m: Member) => void }) {
  const [editing,setEditing]=useState<Member|null>(null);
  const add=()=>setEditing({id:crypto.randomUUID(),household_id:householdId,name:"",role:"parent",profile_color:PROFILE_COLORS[members.length%PROFILE_COLORS.length],restrictions:""});
  return <div className="max-w-3xl mx-auto"><div className="flex items-center justify-between mb-4"><div><h2 className="font-display font-bold text-lg">Profils</h2><p className="text-xs text-faint">Enfants, parents et gardienne peuvent tous avoir leurs restrictions et préférences.</p></div><Button size="sm" onClick={add}><Plus size={14}/> Ajouter un profil</Button></div>{members.length===0?<EmptyState icon={<Users size={28}/>} title="Aucun profil" hint="Ajoute les personnes qui ont des restrictions ou préférences alimentaires."/>:<div className="grid sm:grid-cols-2 gap-3">{members.map(m=><div key={m.id} className="rounded-xl border border-border bg-surface p-4"><div className="flex items-start gap-3"><div className="h-10 w-10 rounded-full text-white flex items-center justify-center font-bold" style={{background:m.profile_color||PROFILE_COLORS[0]}}>{m.name?.[0]||"?"}</div><div className="flex-1"><div className="flex justify-between gap-2"><div><h3 className="font-semibold">{m.name||"Sans nom"}</h3><p className="text-xs text-faint">{m.role==="parent"?"Parent":"Gardienne / responsable"}</p></div><button onClick={()=>setEditing({...m})} className="text-faint hover:text-primary"><Pencil size={15}/></button></div>{m.restrictions&&<p className="text-sm mt-2 text-warning">⚠ {m.restrictions}</p>}</div></div></div>)}</div>}<ProfileDialog member={editing} onClose={()=>setEditing(null)} onSave={m=>{onSave(m);setEditing(null)}}/></div>
}
function ProfileDialog({member,onClose,onSave}:{member:Member|null;onClose:()=>void;onSave:(m:Member)=>void}){const [name,setName]=useState("");const [role,setRole]=useState<Member["role"]>("parent");const [color,setColor]=useState(PROFILE_COLORS[0]);const [restrictions,setRestrictions]=useState("");const [last,setLast]=useState<string|null>(null);if(member&&member.id!==last){setLast(member.id);setName(member.name);setRole(member.role);setColor(member.profile_color||PROFILE_COLORS[0]);setRestrictions(member.restrictions||"")}return <Modal open={!!member} onClose={onClose} title="Profil" footer={<><Button variant="ghost" onClick={onClose}>Annuler</Button><Button onClick={()=>member&&onSave({...member,name:name.trim()||"Sans nom",role,profile_color:color,restrictions:restrictions.trim()})}>Enregistrer</Button></>}><div className="space-y-3"><div><label className="text-xs font-medium text-muted">Nom</label><Input value={name} onChange={e=>setName(e.target.value)} className="mt-1"/></div><div><label className="text-xs font-medium text-muted">Profil</label><select value={role} onChange={e=>setRole(e.target.value as Member["role"])} className="mt-1 w-full rounded-md border border-border bg-surface px-3 py-2 text-sm"><option value="parent">Parent</option><option value="gardienne">Gardienne / responsable</option></select></div><div><label className="text-xs font-medium text-muted">Couleur</label><div className="flex gap-2 mt-2">{PROFILE_COLORS.map(c=><button key={c} onClick={()=>setColor(c)} className="h-7 w-7 rounded-full border-2" style={{background:c,borderColor:color===c?"currentColor":"transparent"}} aria-label="Choisir la couleur"/>)}</div></div><div><label className="text-xs font-medium text-muted">Allergies, restrictions ou préférences</label><Textarea value={restrictions} onChange={e=>setRestrictions(e.target.value)} placeholder="Ex. pas de noix, sans lactose, n'aime pas le poisson…" className="mt-1"/></div></div></Modal>}
