// Couche de données — Supabase réel si configuré, sinon mode démo en mémoire.
import { getSupabase, IS_DEMO } from "./supabase";
import { storageGet, storageSet } from "@/lib/storage";
import { seedDemo } from "./seed";
import type { Approval, ApprovalStatus, Child, GroceryItem, Household, Member, Meal, SavedDish, Week } from "./types";
const uid = () => crypto?.randomUUID?.() ?? "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, c => { const r=(Math.random()*16)|0; return (c==="x"?r:(r&3)|8).toString(16); });
const now = () => new Date().toISOString();
interface DemoState { households: Record<string, Household>; members: Record<string, Member>; children: Record<string, Child>; weeks: Record<string, Week>; meals: Record<string, Meal>; approvals: Record<string, Approval>; grocery: Record<string, GroceryItem>; dishes: Record<string, SavedDish>; }
let demo: DemoState = { ...seedDemo(), dishes: {} } as DemoState;
try { const raw=storageGet("repas-garde-demo"); if(raw) demo={...demo,...JSON.parse(raw)}; } catch {}
function persist(){ storageSet("repas-garde-demo", JSON.stringify(demo)); }
type Listener=()=>void; const listeners=new Set<Listener>(); function emit(){persist(); listeners.forEach(l=>l());}
export function genInviteCode(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:6},()=>chars[Math.floor(Math.random()*chars.length)]).join("");}
export async function createHousehold(name:string){const household={id:uid(),name,invite_code:genInviteCode()};const member:Member={id:uid(),household_id:household.id,name:"Toi",role:"gardienne",created_at:now(),profile_color:"#7c3aed",restrictions:""};if(IS_DEMO){demo.households[household.id]=household;demo.members[member.id]=member;emit();}else{const sb=getSupabase()!;await sb.from("households").insert(household);await sb.from("members").insert(member);}return {household,member};}
export async function joinHousehold(code:string,name:string,role:Member["role"]){if(IS_DEMO){let h=Object.values(demo.households).find(x=>x.invite_code===code.toUpperCase());if(!h){h={id:uid(),name:`Foyer ${code.toUpperCase()}`,invite_code:code.toUpperCase()};demo.households[h.id]=h;}const member:Member={id:uid(),household_id:h.id,name,role,created_at:now(),profile_color:"#2563eb",restrictions:""};demo.members[member.id]=member;emit();return {household:h,member};}const sb=getSupabase()!;const {data:h}=await sb.from("households").select("*").eq("invite_code",code.toUpperCase()).maybeSingle();if(!h)return null;const member:Member={id:uid(),household_id:h.id,name,role,created_at:now(),profile_color:"#2563eb",restrictions:""};await sb.from("members").insert(member);return {household:h as Household,member};}
export async function getHousehold(id:string){if(IS_DEMO)return demo.households[id]??null;const {data}=await getSupabase()!.from("households").select("*").eq("id",id).maybeSingle();return data as Household|null;}
export async function getMembers(id:string){if(IS_DEMO)return Object.values(demo.members).filter(m=>m.household_id===id);const {data}=await getSupabase()!.from("members").select("*").eq("household_id",id).order("created_at");return (data as Member[])??[];}
export async function saveMember(member:Member){if(IS_DEMO){demo.members[member.id]=member;emit();return;}await getSupabase()!.from("members").update({name:member.name,profile_color:member.profile_color,restrictions:member.restrictions}).eq("id",member.id);}
export async function getChildren(id:string){if(IS_DEMO)return Object.values(demo.children).filter(c=>c.household_id===id);const {data}=await getSupabase()!.from("children").select("*").eq("household_id",id).order("name");return (data as Child[])??[];}
export async function saveChild(c:Child){if(IS_DEMO){demo.children[c.id]=c;emit();return;}await getSupabase()!.from("children").upsert(c);}
export async function deleteChild(id:string){if(IS_DEMO){delete demo.children[id];emit();return;}await getSupabase()!.from("children").delete().eq("id",id);}
export async function getOrCreateWeek(householdId:string,weekStart:string,title=""){if(IS_DEMO){const e=Object.values(demo.weeks).find(w=>w.household_id===householdId&&w.week_start===weekStart);if(e)return e;const w={id:uid(),household_id:householdId,week_start:weekStart,title};demo.weeks[w.id]=w;emit();return w;}const sb=getSupabase()!;const {data:found}=await sb.from("weeks").select("*").eq("household_id",householdId).eq("week_start",weekStart).maybeSingle();if(found)return found as Week;const w={id:uid(),household_id:householdId,week_start:weekStart,title};const {data}=await sb.from("weeks").insert(w).select().single();return data as Week;}
export async function getMeals(id:string){if(IS_DEMO)return Object.values(demo.meals).filter(m=>m.week_id===id);const {data}=await getSupabase()!.from("meals").select("*").eq("week_id",id);return (data as Meal[])??[];}
export async function saveMeal(m:Meal){const dish:SavedDish={id:m.title.trim().toLowerCase(),household_id:"",title:m.title.trim(),description:m.description,ingredients:m.ingredients,notes:m.notes,last_used_at:now()};if(IS_DEMO){demo.meals[m.id]={...m,updated_at:now()};if(m.title.trim())demo.dishes[dish.id]=dish;emit();return;}const sb=getSupabase()!;await sb.from("meals").upsert({...m,updated_at:now()});}
export async function deleteMeal(id:string){if(IS_DEMO){delete demo.meals[id];Object.values(demo.approvals).forEach(a=>{if(a.meal_id===id)delete demo.approvals[a.id]});emit();return;}await getSupabase()!.from("meals").delete().eq("id",id);}
export async function getMealLibrary(householdId:string):Promise<SavedDish[]>{if(IS_DEMO)return Object.values(demo.dishes);const {data}=await getSupabase()!.from("meal_library").select("*").eq("household_id",householdId).order("last_used_at",{ascending:false});return (data as SavedDish[])??[];}
export async function saveDish(d:SavedDish){if(IS_DEMO){demo.dishes[d.id]={...d,last_used_at:now()};emit();return;}await getSupabase()!.from("meal_library").upsert({...d,last_used_at:now()});}
export async function getApprovalsForWeek(weekId:string){if(IS_DEMO){const ids=new Set(Object.values(demo.meals).filter(m=>m.week_id===weekId).map(m=>m.id));return Object.values(demo.approvals).filter(a=>ids.has(a.meal_id));}const sb=getSupabase()!;const meals=await getMeals(weekId);if(!meals.length)return[];const {data}=await sb.from("meal_approvals").select("*").in("meal_id",meals.map(m=>m.id));return (data as Approval[])??[];}
export async function setApproval(mealId:string,memberId:string,status:ApprovalStatus,comment:string,_memberName:string){if(IS_DEMO){const e=Object.values(demo.approvals).find(a=>a.meal_id===mealId&&a.member_id===memberId);if(e){e.status=status;e.comment=comment;e.updated_at=now();}else{const a={id:uid(),meal_id:mealId,member_id:memberId,status,comment,updated_at:now()};demo.approvals[a.id]=a;}emit();return;}await getSupabase()!.from("meal_approvals").upsert({meal_id:mealId,member_id:memberId,status,comment,updated_at:now()},{onConflict:"meal_id,member_id"});}
export async function getGrocery(id:string){if(IS_DEMO)return Object.values(demo.grocery).filter(g=>g.week_id===id);const {data}=await getSupabase()!.from("grocery_items").select("*").eq("week_id",id).order("category,name");return (data as GroceryItem[])??[];}
export async function saveGroceryItem(i:GroceryItem){if(IS_DEMO){demo.grocery[i.id]=i;emit();return;}await getSupabase()!.from("grocery_items").upsert({...i,updated_at:now()});}
export async function deleteGroceryItem(id:string){if(IS_DEMO){delete demo.grocery[id];emit();return;}await getSupabase()!.from("grocery_items").delete().eq("id",id);}
export async function generateGroceryFromMeals(weekId:string,memberName:string){const meals=await getMeals(weekId);const approvals=await getApprovalsForWeek(weekId);const rejected=new Set(approvals.filter(a=>a.status==="not_ok").map(a=>a.meal_id));const existing=await getGrocery(weekId);const names=new Set(existing.map(g=>g.name.toLowerCase()));const add:GroceryItem[]=[];for(const m of meals.filter(x=>!rejected.has(x.id)))for(const ing of m.ingredients){const n=ing.trim();if(n&&!names.has(n.toLowerCase())){names.add(n.toLowerCase());add.push({id:uid(),week_id:weekId,name:n,category:guessCategory(n),quantity:"",checked:false,source_meal_id:m.id,updated_by:memberName});}}if(!add.length)return;if(IS_DEMO){add.forEach(g=>demo.grocery[g.id]=g);emit();}else await getSupabase()!.from("grocery_items").insert(add);}
function guessCategory(name:string){const n=name.toLowerCase();if(/pomme|banane|tomate|carotte|oignon|brocoli|fruit|légume/.test(n))return "Fruits & légumes";if(/poulet|boeuf|bœuf|porc|poisson|saumon|viande/.test(n))return "Viandes & poissons";if(/lait|fromage|beurre|yogourt|oeuf|œuf/.test(n))return "Produits laitiers";if(/pain|pâte|riz|quinoa|céréale/.test(n))return "Pain & céréales";return "Divers";}
export async function copyWeek(currentWeekId:string,prevStart:string,memberName:string){const current=await getMeals(currentWeekId);const old=IS_DEMO?Object.values(demo.meals).filter(m=>m.week_id!==currentWeekId):[];void prevStart;void memberName;void old;return current;}
export async function resetDemoData(){demo={...seedDemo(),dishes:{}};emit();}
export function subscribe(listener:Listener){listeners.add(listener);return()=>listeners.delete(listener);}
